services:
  juan-ai:
    image: node:20-alpine
    container_name: j1-ai-chat
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:5173"
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
